### ISSUE TITLE
New Mediapipe Hand Detection Model Don't Work

### ISSUE THREAD

**Issue by HeloWong** [LoSealL/mediapipe-pytorch#1]
New mediapipe hand detection model changed its input shape from [1, 256, 256, 3] to [1, 192, 192, 3], and its construction also changed. Could you tell me how to change it to fit change?

**Comment by LoSealL** [comment]
Check the [blaze_palm.py](https://github.com/LoSealL/mediapipe-pytorch/blob/master/blaze/blaze_palm.py) and to see where to change.

**Comment by HeloWong** [comment]
Got it, Thank you!
